data_science_web_tool/data_science_web_tool/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("general.urls", namespace="general")),
    path("preprocessing/", include("preprocessing.urls", namespace="preprocessing")),
    path("integrations/", include("integrations.urls", namespace="integrations")),
    path(
        "linear_regression/",
        include("linear_regression.urls", namespace="linear_regression"),
    ),
    path(
        "garch/",
        include("garch.urls", namespace="garch"),
    ),
]

data_science_web_tool/garch/urls.py
from django.urls import path
from garch import views

app_name = "garch"


urlpatterns = [
    path(
        "<int:pk>/",
        views.GarchResultView.as_view(),
        name="garch-details",
    ),
    path(
        "create/",
        views.GarchResultCreateAPIView.as_view(),
        name="garch-create",
    ),
]

data_science_web_tool/preprocessing/urls.py
from django.urls import path

from preprocessing import views

app_name = "preprocessing"


urlpatterns = [
    path("<int:pk>/", views.DataDetailView.as_view(), name="data-detail"),
    path(
        "<int:pk>/change-column-type/",
        views.ChangeColumnTypeCreateAPIView.as_view(),
        name="change-column-type",
    ),
    path(
        "<int:pk>/create-plot/",
        views.ImageCreateAPIView.as_view(),
        name="create-plot",
    ),
    path(
        "<int:pk>/stationary-tests/",
        views.CreateStationaryTestResultsAPIView.as_view(),
        name="create-stationary-test-results",
    ),
]

data_science_web_tool/preprocessing/models.py
import io

import pandas as pd
from django.db import models
from django.urls import reverse
from django.utils.html import format_html

from preprocessing.data_sources_handlers.csv_source_handler import CsvDataSourceHandler
from preprocessing.data_sources_handlers.yfinance_source_handler import YFinanceDataSourceHandler
from preprocessing.plot_handlers.histogram import HistogramPlotHandler
from preprocessing.plot_handlers.line_plot import LinePlotHandler
from preprocessing.statistics_tests_handlers.adf_test import ADFTestHandler


class Data(models.Model):
    NUMERICAL_TYPES = (
        "int64",
        "float64",
    )
    SUPPORTED_COLUMN_TYPES = (
        "int64",
        "float64",
        "object",
        "bool",
        "datetime64[ns]",
        "category",
    )
    SUPPORTED_PLOT_TYPES = {
        "sns.lineplot": LinePlotHandler,
        "sns.histplot": HistogramPlotHandler,
    }

    class Meta:
        verbose_name_plural = "data"

    name = models.CharField(max_length=256, help_text="Name of the data source.")
    description = models.TextField(null=True, blank=True, help_text="Additional information about the data source.")
    data = models.JSONField(null=True, blank=True)
    data_index = models.JSONField(
        null=True,
        blank=True,
        default=list,
        help_text="DataFrame indexes defined by the user. Must match possible column names.",
    )
    data_columns = models.JSONField(
        null=True,
        blank=True,
        default=dict,
        help_text="Found DataFrame columns.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.data_columns:
            df: pd.DataFrame = self.get_df()
            self.data_columns = {str(key): str(value) for key, value in df.dtypes.to_dict().items()}
        super().save(*args, **kwargs)

    def get_admin_change_url(self) -> str:
        url = reverse("admin:preprocessing_data_change", args=[self.pk])
        return format_html('<a href="{}">{}</a>', url, self.name)

    def get_statistics(self):
        df: pd.DataFrame = self.get_df()
        if df.empty:
            return {}

        # Capture info() output as a string
        buffer = io.StringIO()
        df.info(buf=buffer)
        info_text = buffer.getvalue().replace("\n", "<br>")
        return {
            "describe": df.describe().T.to_html(
                classes="table table-bordered table-sm",
            ),
            "head": df.head(5).to_html(classes="table table-bordered table-sm"),
            "info": info_text,
        }

    def get_df(self) -> pd.DataFrame:
        df = pd.DataFrame(self.data)
        df = df.astype(self.data_columns)
        if self.data_index:
            df.set_index(self.data_index, inplace=True)
            df = df.sort_index()
        return df

    def __str__(self) -> str:
        return f"Data `{self.name}`"


class DataUpload(models.Model):
    FILE_TYPE_CSV = "csv"
    YFINANACE = "yfinance"
    DATA_SOURCE_CHOICES = (
        (FILE_TYPE_CSV, FILE_TYPE_CSV),
        (YFINANACE, YFINANACE),
    )
    DATA_SOURCE_TYPE_PROCESSORS = {
        "csv": CsvDataSourceHandler,
        "yfinance": YFinanceDataSourceHandler,
    }

    file_name = models.CharField(max_length=512)
    file_type = models.CharField(max_length=32, choices=DATA_SOURCE_CHOICES)
    description = models.TextField(null=True, blank=True)

    file = models.FileField(upload_to="uploads/")
    data = models.OneToOneField(
        Data,
        related_name="data_upload",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.file and not self.file_name:
            self.file_name = self.file.name

        if self.file and self.data is None:
            file_handler = self.DATA_SOURCE_TYPE_PROCESSORS.get(self.file_type)
            if not file_handler:
                raise TypeError(f"File type '{self.file_type}' is not supported")

            data = file_handler(self.file).load_data()
            self.data = Data.objects.create(
                name=self.file_name,
                description=self.description,
                data=data,
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Data {self.file} uploaded at {self.created_at.isoformat()}"


class DataTestResult(models.Model):
    SUPPORTED_TEST_HANDLERS = {
        "adf": ADFTestHandler,
    }

    data = models.ForeignKey(Data, on_delete=models.CASCADE)
    results = models.JSONField(null=True, blank=True)

    test_type = models.CharField(null=True, blank=True)
    target_column = models.CharField(null=True, blank=True)
    max_augmentation_count = models.IntegerField(null=True, blank=True)
    test_version = models.CharField(null=True, blank=True)
    differentiate_count = models.IntegerField(null=True, blank=True)

    raw_data_pp_test_results = models.JSONField(null=True, blank=True)
    raw_data_kpss_test_results = models.JSONField(null=True, blank=True)
    diff_data_pp_test_results = models.JSONField(null=True, blank=True)
    diff_data_kpss_test_results = models.JSONField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

data_science_web_tool/preprocessing/views.py
from typing import Callable

import pandas as pd
from arch.unitroot import PhillipsPerron
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.generic import DetailView
from rest_framework.exceptions import ValidationError
from rest_framework.generics import CreateAPIView
from statsmodels.tsa.stattools import kpss

from preprocessing.models import Data
from preprocessing.models import DataTestResult
from preprocessing.serializers.serializers import CreateStationaryTestRequestSerializer
from preprocessing.serializers.serializers import ImageRetrieveSerializer


class DataDetailView(DetailView):
    model = Data
    template_name = "preprocessing/data/details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["statistics"] = self.object.get_statistics()
        context["preprocessing_plot_image"] = self.request.session.pop("preprocessing_plot_image", None)
        context["preprocessing_plot_axis_x_name"] = self.request.session.pop("preprocessing_plot_axis_x_name", None)
        context["preprocessing_plot_axis_y_name"] = self.request.session.pop("preprocessing_plot_axis_y_name", None)
        context["preprocessing_group_by_name"] = self.request.session.pop("preprocessing_group_by_name", None)
        context["preprocessing_plot_type"] = self.request.session.pop("preprocessing_plot_type", None)
        context["image_validation_errors"] = self.request.session.pop("image_validation_errors", None)
        context["is_group_by_disabled"] = not bool(
            any(value_type == "category" for value_type in self.object.data_columns.values())
        )
        context["numerical_columns"] = [
            column_name
            for column_name, column_type in self.object.data_columns.items()
            if column_type in Data.NUMERICAL_TYPES
        ]

        last_adf_test = DataTestResult.objects.filter(test_type="adf").order_by("-created_at").first()
        if not last_adf_test:
            return context

        adf_results = last_adf_test.results
        context["last_adf_test_results"] = adf_results if last_adf_test else None
        context["last_adf_test_target_column"] = last_adf_test.target_column
        context["last_adf_test_results_indices"] = list(list(adf_results.values())[0].keys())
        context["last_adf_test_results_max_augmentation_count"] = last_adf_test.max_augmentation_count
        context["last_adf_test_datetime"] = last_adf_test.created_at if last_adf_test else None
        context["last_adf_test_results_differentiate_count"] = last_adf_test.differentiate_count
        context["last_adf_test_results_test_version"] = last_adf_test.test_version
        context["raw_data_pp_test_results"] = last_adf_test.raw_data_pp_test_results
        context["diff_data_pp_test_results"] = last_adf_test.diff_data_pp_test_results
        if last_adf_test.raw_data_kpss_test_results:
            context["raw_data_kpss_test_results"] = {
                "p_value": round(last_adf_test.raw_data_kpss_test_results.get("p_value", 0), 6),
                "test_statistic": round(last_adf_test.raw_data_kpss_test_results.get("test_statistic", 0), 6),
            }
        if last_adf_test.diff_data_kpss_test_results:
            context["diff_data_kpss_test_results"] = {
                "p_value": round(last_adf_test.diff_data_kpss_test_results.get("p_value", 0), 6),
                "test_statistic": round(last_adf_test.diff_data_kpss_test_results.get("test_statistic", 0), 6),
            }
        context["last_adf_test_results_highlight_indices"] = self.__adf_get_first_correct_row_index(adf_results)
        return context

    @staticmethod
    def __adf_get_first_correct_row_index(adf_results: dict) -> list[int]:
        min_p_value = 0.05
        highlight_indices = []

        for idx, value in adf_results["ADF Test statistic"].items():
            pval_5 = adf_results["Test BG (5 lags) (p-value)"][idx]
            pval_10 = adf_results["Test BG (10 lags) (p-value)"][idx]
            pval_15 = adf_results["Test BG (15 lags) (p-value)"][idx]

            critical_value_1 = adf_results["Critical Value ADF (1%)"][idx]
            critical_value_5 = adf_results["Critical Value ADF (5%)"][idx]
            critical_value_10 = adf_results["Critical Value ADF (10%)"][idx]

            if pval_5 > min_p_value and pval_10 > min_p_value and pval_15 > min_p_value:
                if value < critical_value_1 and value < critical_value_5 and value < critical_value_10:
                    highlight_indices.append(idx)
                    return highlight_indices
        return []


class CreateStationaryTestResultsAPIView(CreateAPIView):
    model = Data
    serializer_class = CreateStationaryTestRequestSerializer

    def create(self, request, *args, **kwargs):
        instance: Data = get_object_or_404(Data, id=self.kwargs.get("pk", ""))
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid(raise_exception=False):
            request.session["image_validation_errors"] = serializer.errors
            return redirect("preprocessing:data-detail", pk=instance.id)

        validated_data = serializer.validated_data
        test_handler = DataTestResult.SUPPORTED_TEST_HANDLERS.get(validated_data["test_type"])
        df: pd.DataFrame = instance.get_df()
        differentiate_count = validated_data["differentiate_count"]

        time_series = df[validated_data["target_column"]]
        test_handler_instance = test_handler(
            series=time_series.copy(),
            max_aug=validated_data["max_augmentation_count"],
            version=validated_data["test_version"],
            differentiate_count=differentiate_count,
        )
        adf_test_results: pd.DataFrame = test_handler_instance.run()

        raw_data_pp_test = PhillipsPerron(time_series.copy(), trend="n")
        raw_data_kpss_stat, raw_data_kpss_p_value, _, _ = kpss(time_series.copy(), regression="c")

        if differentiate_count > 0:
            for i in range(differentiate_count):
                time_series = time_series.diff().dropna()

        diff_data_pp_test = PhillipsPerron(time_series.copy(), trend="n")
        diff_data_kpss_stat, diff_data_kpss_p_value, _, _ = kpss(time_series.copy(), regression="c")

        DataTestResult.objects.create(
            data=instance,
            results=adf_test_results.to_dict(),
            raw_data_pp_test_results={
                "test_statistic": raw_data_pp_test.stat,
                "p_value": raw_data_pp_test.pvalue,
                "summary": str(raw_data_pp_test.summary()),
            },
            raw_data_kpss_test_results={"test_statistic": raw_data_kpss_stat, "p_value": raw_data_kpss_p_value},
            diff_data_kpss_test_results={"test_statistic": diff_data_kpss_stat, "p_value": diff_data_kpss_p_value},
            diff_data_pp_test_results={
                "test_statistic": diff_data_pp_test.stat,
                "p_value": diff_data_pp_test.pvalue,
                "summary": str(diff_data_pp_test.summary()),
            },
            **validated_data,
        )

        return redirect("preprocessing:data-detail", pk=instance.id)


class ChangeColumnTypeCreateAPIView(CreateAPIView):
    queryset = Data.objects.all()
    serializer_class = None

    def create(self, request, *args, **kwargs):
        """
        Tries to change column type of selected data frame.
        Returns HTTP 400 Bad Request if operation fails.
        """
        instance: Data = get_object_or_404(Data, id=self.kwargs.get("pk", ""))
        column_types = {}
        current_columns = list(instance.data_columns.keys())
        for key, value in request.POST.items():
            if not key.startswith("data_type_"):
                continue

            new_type = request.POST.get(key, "")
            if not new_type or new_type not in Data.SUPPORTED_COLUMN_TYPES:
                messages.error(request, "Invalid column type.")
                return redirect("preprocessing:data-detail", pk=instance.id)

            column_name = key.replace("data_type_", "")
            if column_name not in current_columns:
                messages.error(request, "Invalid column name.")
                return redirect("preprocessing:data-detail", pk=instance.id)

            column_types[column_name] = new_type

        instance.data_columns = column_types
        is_success = True
        try:
            instance.save()
        except Exception as e:
            is_success = False
            messages.error(request, str(e))

        if is_success:
            messages.success(request, "Column types updated successfully!")

        return redirect("preprocessing:data-detail", pk=instance.id)


class ImageCreateAPIView(CreateAPIView):
    queryset = Data.objects.all()
    serializer_class = ImageRetrieveSerializer

    def create(self, request, *args, **kwargs):
        """
        Generate requested plot and return it as an image.
        """
        instance: Data = get_object_or_404(Data, id=self.kwargs.get("pk", ""))
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid(raise_exception=False):
            request.session["image_validation_errors"] = serializer.errors
            return redirect("preprocessing:data-detail", pk=instance.id)

        validated_data = serializer.validated_data

        plot_handler: Callable = instance.SUPPORTED_PLOT_TYPES.get(validated_data["plot_type"])
        if not plot_handler:
            raise ValidationError("Invalid plot type.")

        image: str = plot_handler(
            data=instance,
            axis_x_name=validated_data["axis_x_name"],
            axis_y_name=validated_data["axis_y_name"],
            group_by_name=validated_data.get("group_by_name"),
        ).create_image()
        request.session["preprocessing_plot_image"] = image

data_science_web_tool/preprocessing/templates/preprocessing/components/create_image.html
<h3>Plot Data</h3>
<div class="card mb-4">
    <div class="card-header"><strong>Select Plot Type & Column</strong></div>
    <div class="card-body">
        <form method="POST" action="{% url 'preprocessing:create-plot' object.id %}">
            {% csrf_token %}
            <div class="row g-3 align-items-end">

                <!-- Select Plot Type -->
                <div class="col-md-3">
                    <label for="plotType" class="form-label">Plot Type</label>
                    <select class="form-select" id="plotType" name="plot_type" required>
                        {% for supported_plot_type in object.SUPPORTED_PLOT_TYPES %}
                            <option value="{{ supported_plot_type }}" {% if supported_plot_type == preprocessing_plot_type %}selected{% endif %}>
                                {{ supported_plot_type }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Select Column X -->
                <div class="col-md-3">
                    <label for="plotColumnX" class="form-label">Axis X</label>
                    <select class="form-select" id="plotColumnX" name="axis_x_name" required>
                        <option value="-">-</option>
                        {% for column_name in object.data_columns.keys%}
                            <option value="{{ column_name }}" {% if column_name|lower == preprocessing_plot_axis_x_name %}selected{% endif %}>
                                {{ column_name|title }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Select Column Y -->
                <div class="col-md-3">
                    <label for="plotColumnY" class="form-label">Axis Y</label>
                    <select class="form-select" id="plotColumnY" name="axis_y_name" required>
                        <option value="-">-</option>
                        {% for column_name in object.data_columns.keys%}
                            <option value="{{ column_name }}" {% if column_name|lower == preprocessing_plot_axis_y_name %}selected{% endif %}>
                                {{ column_name|title }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Select Column Group By -->
                <div class="col-md-3">
                    <label for="plotGroupBy" class="form-label">Group By</label>
                    {% if is_group_by_disabled %}
                        <span data-bs-toggle="tooltip" title="No Categories to Group By.">
                            <select class="form-select" id="plotGroupBy" name="group_by_name" disabled>
                                <option value="-">-</option>
                            </select>
                        </span>
                    {% else %}
                        <select class="form-select" id="plotGroupBy" name="group_by_name">
                            <option value="-">-</option>
                            {% for column_name, column_value in object.data_columns.items %}
                                {% if column_value == 'category' %}
                                    <option value="{{ column_name }}" {% if column_name == preprocessing_group_by_name %}selected{% endif %}>
                                        {{ column_name|title }}
                                    </option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
                <!-- Submit Button -->
                <div class="col-12">
                    <button type="submit" class="btn btn-primary w-100">Generate Plot</button>
                </div>
            </div>
        </form>
    </div>

    <!-- Image validation errors -->
    {% if image_validation_errors %}
        <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
            {% for error_msg in image_validation_errors.non_field_errors %}
                {{ error_msg|capfirst }}
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <!-- Display Generated Plot -->
    {% if preprocessing_plot_image %}
        <div class="row">
            <div class="mt-4 col-12 text-center">
                <img id="plotResult" src="{{ preprocessing_plot_image  }}" alt="Plot of {{ preprocessing_plot_image }}" class="img-fluid rounded">
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-12 mt-3 ml-5 text-muted">
                <p>No image available.</p>
            </div>
        </div>
    {% endif %}
</div>


<script>
  window.onload = function () {
    const imagePlot = document.getElementById("plotResult");
    if (imagePlot) {
      imagePlot.scrollIntoView({ behavior: "smooth" });
    }
  };
</script>