data_science_web_tool/data_science_web_tool/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("general.urls", namespace="general")),
    path("preprocessing/", include("preprocessing.urls", namespace="preprocessing")),
    path("integrations/", include("integrations.urls", namespace="integrations")),
    path(
        "linear_regression/",
        include("linear_regression.urls", namespace="linear_regression"),
    ),
    path(
        "garch/",
        include("garch.urls", namespace="garch"),
    ),
]

data_science_web_tool/garch/urls.py
from django.urls import path
from garch import views

app_name = "garch"


urlpatterns = [
    path(
        "<int:pk>/",
        views.GarchResultView.as_view(),
        name="garch-details",
    ),
    path(
        "create/",
        views.GarchResultCreateAPIView.as_view(),
        name="garch-create",
    ),
]

data_science_web_tool/general/urls.py
from django.urls import path

from general import views

app_name = "general"


urlpatterns = [
    path("", views.DataListView.as_view(), name="data-list"),
]

data_science_web_tool/integrations/urls.py
from django.urls import path

from integrations import views

app_name = "integrations"


urlpatterns = [
    path("yfinance/", views.YahooFinanceListView.as_view(), name="yahoo-finance-list"),
    path(
        "yfinance/download/",
        views.YahooFinanceUploadCreateView.as_view(),
        name="yahoo-finance-download",
    ),
]

data_science_web_tool/linear_regression/urls.py
from django.urls import path

from linear_regression import views

app_name = "linear_regression"


urlpatterns = [
    path(
        "<int:pk>/",
        views.LinearRegressionView.as_view(),
        name="linear-regression-details",
    ),
    path(
        "time-series/create/",
        views.LinearRegressionTimeSeriesCreateAPIView.as_view(),
        name="linear-regression-time-series-create",
    ),
]

data_science_web_tool/preprocessing/urls.py
from django.urls import path

from preprocessing import views

app_name = "preprocessing"


urlpatterns = [
    path("<int:pk>/", views.DataDetailView.as_view(), name="data-detail"),
    path(
        "<int:pk>/change-column-type/",
        views.ChangeColumnTypeCreateAPIView.as_view(),
        name="change-column-type",
    ),
    path(
        "<int:pk>/create-plot/",
        views.ImageCreateAPIView.as_view(),
        name="create-plot",
    ),
    path(
        "<int:pk>/stationary-tests/",
        views.CreateStationaryTestResultsAPIView.as_view(),
        name="create-stationary-test-results",
    ),
]

data_science_web_tool/general/models.py
# Create your models here.

data_science_web_tool/general/views.py
from django.views.generic import ListView

from preprocessing.models import Data


class DataListView(ListView):
    model = Data
    queryset = Data.objects.all().order_by("-created_at")
    template_name = "general/data/list.html"
    paginate_by = 10

data_science_web_tool/general/templates/general/data/list.html
{% extends "common/base.html" %}

{% block title %}List of uploaded data entries{% endblock %}

{% block content %}
<div class="d-flex align-items-center">
    <h1 class="mb-1 me-4">List of uploaded data entries</h1>
    <a href="{% url 'admin:preprocessing_dataupload_changelist' %}" class="btn btn-primary btn-sm me-2">Add manually</a>
    <a href="{% url 'integrations:yahoo-finance-list' %}" class="btn btn-primary btn-sm me-2">yFinance</a>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 15%">Name</th>
                <th style="width: 29%">Details</th>
                <th style="width: 8%">Created At</th>
                <th style="width: 8%">Updated At</th>
                <th style="width: 10%">Admin Page</th>
                <th style="width: 10%">Preprocessing</th>
                <th style="width: 10%">Linear Regression</th>
                <th style="width: 10%">Arch | Garch</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj  }}</td>
                    <td>{{ obj.created_at|date:"Y-m-d H:i" }}</td>
                    <td>{{ obj.updated_at|date:"Y-m-d H:i" }}</td>
                    <td>{{ obj.get_admin_change_url }}</td>
                    <td><a href="{% url 'preprocessing:data-detail' obj.pk %}">Preprocess</a></td>
                    <td><a href="{% url 'linear_regression:linear-regression-details' obj.pk %}">Linear Regression</a></td>
                    <td><a href="{% url 'garch:garch-details' obj.pk %}">Arch | Garch</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">No objects available.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include "common/pagination.html" with page=page_obj %}
{% endblock %}